# Label for changes in devops files
devops:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: '.husky/**'
      - any-glob-to-any-file: 'Makefile'

# Label for changes in documentation
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

# Label for changes in JS files
js:
  - changed-files:
      - any-glob-to-any-file: '**/*.js'

# Label for changes in YAML files
yaml:
  - changed-files:
      - any-glob-to-any-file: '**/*.yml'
      - any-glob-to-any-file: '**/*.yaml'

# Label for changes in JSON files
json:
  - changed-files:
      - any-glob-to-any-file: '**/*.json'

# Label for changes in dependency files
dependencies:
  - changed-files:
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'package-lock.json'

# Label for changes in configuration files
configuration:
  - changed-files:
      - any-glob-to-any-file: '.depkit.json'
      - any-glob-to-any-file: '.editorconfig'
      - any-glob-to-any-file: '.gitignore'
      - any-glob-to-any-file: '.lintrc.json'
      - any-glob-to-any-file: '.markdownlint.json'
      - any-glob-to-any-file: '.prettierignore'
      - any-glob-to-any-file: '.prettierrc.json'
      - any-glob-to-any-file: 'commitlint.config.js'
      - any-glob-to-any-file: 'cspell.json'
      - any-glob-to-any-file: 'eslint.config.js'
      - any-glob-to-any-file: 'release.config.js'
      - any-glob-to-any-file: 'release.update.js'
