name: 'Pull Request Labeler'

on:
  - pull_request_target

jobs:
  labeler:
    uses: ./.github/workflows/pr-labeler.yml
    with:
      VERBOSE: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      issues: write
      contents: read
      pull-requests: write
