name: PR Labeler

on:
  workflow_call:
    inputs:
      VERBOSE:
        type: boolean
        default: false
        required: false
        description: 'Enable verbose output'
    secrets:
      GH_TOKEN:
        required: true
        description: 'GitHub token for authentication'

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        if: ${{ inputs.VERBOSE }}
        shell: bash
        run: |
          echo "VERBOSE: ${{ inputs.VERBOSE }}"
          echo "GH_TOKEN is set: ${{ secrets.GH_TOKEN != '' }}"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Labeler
        uses: actions/labeler@v5
        with:
          sync-labels: true
